apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-migrate
  labels:
    app: odoo-migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-migrate
  template:
    metadata:
      name: odoo-migrate
      labels:
        app: odoo-migrate
    spec:
      containers:
        - name: odoo-migrate
          image: vladimirovrosen/odoo-migrate-tool:2.12
          imagePullPolicy: Always
          env:
            - name: EXECUTE
              value: 1,2
          volumeMounts:
            - mountPath: /etc/odoo/main.ini
              name: conf
              subPath: main.ini
      volumes:
      - name: conf
        configMap:
          name: odoo-migrate-config-data

